# Generated by Django 4.2.4 on 2023-08-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
