# Generated by Django 4.2.4 on 2023-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
