# Generated by Django 4.2.4 on 2023-09-05 03:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="amirreza-",
                editable=False,
                populate_from="username",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
