# Generated by Django 4.2.4 on 2023-09-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inlinedescription",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descriptions",
                to="records.condition",
            ),
        ),
    ]
