# Generated by Django 4.2.4 on 2023-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_alter_inlinedescription_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
