# Generated by Django 4.2.4 on 2023-09-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_alter_medicine_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        max_length=255, verbose_name="name of the condition"
                    ),
                ),
                ("info", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="condition",
            name="condition",
        ),
        migrations.AddField(
            model_name="condition",
            name="conditions",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="records.conditioninfo",
            ),
            preserve_default=False,
        ),
    ]
