# Generated by Django 4.2.7 on 2023-11-09 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0004_conditioninfo_remove_condition_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condition",
            name="medicines",
        ),
        migrations.AddField(
            model_name="condition",
            name="medicine",
            field=models.ManyToManyField(to="records.medicine"),
        ),
        migrations.AlterField(
            model_name="condition",
            name="conditions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_info",
                to="records.conditioninfo",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="conditioninfo",
            name="condition",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="medicine",
            field=models.CharField(max_length=255),
        ),
    ]
