# Generated by Django 4.2.8 on 2023-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0005_remove_condition_medicines_condition_medicine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="MRI",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
    ]
